### ISSUE TITLE
After locking, unlocking fails.

### ISSUE THREAD

**Issue by generic-user** [vipzhicheng/logseq-plugin-lock#2]
When I lock something with ea the password "1", it fails to unlock it.

## See this video

[![Alt text](https://img.youtube.com/vi/CXD5isoh_4Y/0.jpg)](https://youtu.be/CXD5isoh_4Y)

Any thoughts?

**Comment by bcohen44** [comment]
Also seeing this.  Plugin is unusable right now, **unlocking does not work at all.**

This is as of Logseq version 0.5.3

**Comment by AvijeetPrasad** [comment]
I also faced the same issue on Logseq 0.5.4.

The plugin is able to lock the content as expected, but the unlocking completely fails.

**Comment by bcohen44** [comment]
Updated to 0.0.2 (and Logseq 0.5.9), and the unlock issues still persists.

**Comment by vipzhicheng** [comment]
Sorry about that, I have dug into it a couple of hours and finally fixed it, please update from the marketplace at least v0.0.5.

**Comment by vipzhicheng** [comment]
Closed!
