### ISSUE TITLE
Encrypt Block with its nested blocks?

### ISSUE THREAD

**Issue by L0cutus** [vipzhicheng/logseq-plugin-lock#3]
Hello!
What about subject?

**Comment by vipzhicheng** [comment]
My initial design is to encrypt the current block and can not be decrypted. That makes me feel safe. Speaking of encrypting nested blocks I think that would be possible, but would not be in this plugin, and I can not imagine the scenario. The purpose of this plugin is to save my passwords, so I don't what them to be decrypted.

Even if I can implement this idea, it's hard to keep all block properties when decrypting that would cause issues with Logseq.
