### ISSUE TITLE
Hello, would it be possible to make it so that when you click on the icon, it prompts the password menu?

### ISSUE THREAD

**Issue by pikacho13** [vipzhicheng/logseq-plugin-lock#4]
Thanks for making an option to encrypt specific blocks!
Would it be possible to use the icon, as it seems right now you can only right click on the bullet (or the /lock) command, but it seems like it'd make the process a bit quicker/smoother if clicking the icon could do it. I have no clue how these work so sorry if it's not really possible to do with the plugin, but thanks for considering it!

**Comment by pikacho13** [comment]
Oh also, is there a possibility to make it show the content, like how it works in Roam Research?
This tweet shows how it looks. The content seems to still exist within the encryption, but we can see it. Just takes away the need to paste it elsewhere to see the content.
https://twitter.com/roamresearch/status/1226658292333568003?lang=en

**Comment by vipzhicheng** [comment]
There is a shortcut for you to trigger lock UI quicker.

But I think Logseq is a little bit different from Roam. In Roam your data is stored in Roam Server, but in Logseq, your data is on your local storage. So the concern is different. what I design for is the case that anybody gets your computer and data, but he can still not know what it is even he know your graph password if you encrypt it using Logseq experimental feature.

Another case for me is to store my many internet account password, When I need to login, I just push it to clipboard, and login, not need to know what it is.

**Comment by pikacho13** [comment]
Ah that makes sense! thanks for responding :)
